version: "3"

volumes:
  pg_data:
services:
  spark-geolake:
    image: spatialx/spark-geolake
    container_name: spark-geolake
    build: spark/
    depends_on:
      - postgres
    volumes:
      - ./spark/data:/home/iceberg/data
      - ./spark/notebooks:/home/iceberg/notebooks
    environment:
      - SPARK_HOME=/opt/spark
      - PYSPARK_PYTON=/usr/bin/python3.9
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/spark/bin
    ports:
      - 4041:4041
      - 4042:4042
      - 4043:4043
      - 8888:8888
      - 8080:8080
      - 18080:18080
  postgres:
    image: postgres:13.4-bullseye
    container_name: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=demo_catalog
    volumes:
      - pg_data:/var/lib/postgresql/data
